entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  le:
    acme:
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

api:
  insecure: false
  dashboard: false

log:
  level: INFO

accessLog:
  filePath: /dev/stdout

global:
  sendAnonymousUsage: false

